Repository stolostron/insights-client, pull requests merged in 2021-08, with the labels that each got.

#55 Remove publish job
  .travis.yml
Labels: lgtm, approved

#59 add make target for lint
  Makefile.prow
Labels: lgtm, approved, dco-signoff: yes

#57 Add governance violations to results in policyReports
  pkg/processor/reportprocessor.go
  pkg/processor/reportprocessor_test.go
Labels: lgtm, dco-signoff: yes

#61 [release 2.3] image rebuild
  README.md
Labels: lgtm, approved, dco-signoff: yes
