Repository stolostron/insights-client, pull requests merged in 2021-04, with the labels that each got.

#14 added content length log message
  pkg/retriever/reportretriever.go
Labels: approved, lgtm

#13 Create & update PolicyReport resources from Insights reports
  go.sum
  main.go
  pkg/config/config_test.go
  pkg/config/kubeClient.go
  pkg/processor/reportprocessor.go
  pkg/retriever/contentretriever.go
  pkg/retriever/contentretriever_test.go
  pkg/retriever/reportretriever.go
  pkg/retriever/reportretriever_test.go
  pkg/types/contentTypes.go
  pkg/types/policyReportTypes.go
Labels: approved, lgtm

#15 migrated policyreport to v1alpha2
  go.mod
  go.sum
  pkg/config/kubeClient.go
  pkg/processor/reportprocessor.go
Labels: approved, lgtm

#16 updated health probes
  main.go
  pkg/handlers/healthProbes.go
  pkg/monitor/clustermonitor.go
  pkg/processor/reportprocessor.go
  pkg/retriever/reportretriever.go
Labels: approved, lgtm

#17 refresh token before every report fetch
  main.go
  pkg/monitor/clustermonitor.go
  pkg/monitor/clustermonitor_test.go
  pkg/retriever/contentretriever_test.go
  pkg/retriever/reportretriever.go
  pkg/retriever/reportretriever_test.go
Labels: approved, do-not-merge/hold

#18 update owners and base image
  Dockerfile
  Dockerfile.prow
  OWNERS
Labels: approved, lgtm

#20 fixed details object type
  pkg/types/policyReportTypes.go
Labels: approved, lgtm

#22 use clusterversions for getting hub cluster id
  pkg/monitor/clustermonitor.go
  pkg/monitor/clustermonitor_test.go
  test-data/managed-cluster.json
Labels: approved, do-not-merge/hold, lgtm

#25 add e2e tests
  .travis.yml
  Makefile
  build/run-e2e-tests.sh
  pkg/config/config.go
  test-data/e2e/clusterversions.config.openshift.io.yaml
  test-data/e2e/insights-chart/templates/insights-deployment.yaml
  test-data/e2e/insights-chart/templates/insights-role-binding.yaml
  test-data/e2e/insights-chart/templates/insights-role.yaml
  test-data/e2e/insights-chart/templates/insights-service-account.yaml
  test-data/e2e/insights-chart/templates/insights-service.yaml
  test-data/e2e/kind-hub-config.yaml
  test-data/e2e/local-clusterCR.yaml
  test-data/e2e/managedclusters.yaml
  test-data/e2e/version.yaml
Labels: approved, do-not-merge/hold, lgtm

#23 Only create one PolicyReport per cluster
  main.go
  pkg/config/kubeClient.go
  pkg/processor/reportprocessor.go
  pkg/types/policyReportTypes.go
Labels: approved, lgtm
