Repository stolostron/insights-client, pull requests merged in 2021-03, with the labels that each got.

#3 initial commit for CRC authorization
  .gitignore
  .travis.yml
  COMPONENT_NAME
  COMPONENT_VERSION
  Dockerfile
  Makefile
  RELEASE_FF_BRANCH
  RELEASE_MAIN_BRANCH
  build/Configfile
  build/build.sh
  build/deploy-to-cluster.sh
  build/install-dependencies.sh
  build/run-e2e-tests.sh
  build/run-unit-tests.sh
  go.mod
  go.sum
  main.go
  pkg/config/config.go
  pkg/config/kubeClient.go
  pkg/handlers/healthProbes.go
  pkg/retriever/reportretriever.go
  pkg/retriever/reportretriver_test.go
  pkg/types/types.go
  pkg/utils/34c3ecc5-624a-49a5-bab8-4fdc5e51a266.json
  pkg/utils/utils.go
  setup.sh
  sonar-project.properties
  sslcert/README.md
  sslcert/req.conf
Labels: approved

#4 Fix Readme repo name
  README.md
Labels: approved, lgtm

#7 updated types to get CRC json
  pkg/retriever/reportretriever.go
  pkg/retriever/reportretriver_test.go
  pkg/types/types.go
Labels: approved, lgtm

#5 Get cluster ids of all managed clusters for insights
  go.mod
  go.sum
  main.go
  pkg/config/kubeClient.go
  pkg/monitor/clustermonitor.go
  pkg/monitor/clustermonitor_test.go
  pkg/retriever/reportretriever_test.go
  pkg/types/managedClusterTypes.go
  pkg/types/policyReportTypes.go
  test-data/managed-cluster.json
Labels: approved

#8 Include managed cluster IDs after they are upgraded to 4.X
  pkg/monitor/clustermonitor.go
Labels: approved, lgtm

#9 Get contents from CRC and keep in cache for lookup
  main.go
  pkg/monitor/clustermonitor.go
  pkg/retriever/reportretriever.go
  pkg/retriever/reportretriever_test.go
  pkg/types/contentTypes.go
  pkg/utils/content.json
  pkg/utils/utils.go
Labels: approved, lgtm

#11 fixed comments per pr review
  main.go
  pkg/retriever/reportretriever.go
Labels: approved, do-not-merge/hold, lgtm

#10 Use managed cluster list to retrieve Insight reports
  main.go
  pkg/monitor/clustermonitor.go
  pkg/monitor/clustermonitor_test.go
  pkg/retriever/reportretriever.go
  pkg/retriever/reportretriever_test.go
Labels: approved, lgtm
