Repository stolostron/insights-client, pull requests merged in 2021-05, with the labels that each got.

#27 Xav/pollinterval
  main.go
  pkg/config/config.go
  pkg/monitor/clustermonitor.go
  pkg/monitor/clustermonitor_test.go
Labels: approved, do-not-merge/hold, lgtm

#29 Add a pause between cluster report requests
  pkg/config/config.go
  pkg/retriever/reportretriever.go
Labels: approved, lgtm

#26 Update lifecycle of PolicyReport resource
  main.go
  pkg/processor/reportprocessor.go
  pkg/types/contentTypes.go
  pkg/types/policyReportTypes.go
Labels: approved, lgtm

#30 Add ability to set ca cert to use qaprodauth
  README.md
  pkg/config/config.go
  pkg/monitor/clustermonitor.go
  pkg/processor/reportprocessor.go
  pkg/retriever/contentretriever.go
  pkg/retriever/reportretriever.go
  pkg/types/policyReportTypes.go
Labels: approved, do-not-merge/hold

#31 Fix type for response body errors array
  pkg/retriever/reportretriever.go
  pkg/types/policyReportTypes.go
Labels: approved, lgtm

#32 Add check to filter out the tutorial insight
  pkg/processor/reportprocessor.go
Labels: approved, lgtm

#34 Create a configmap to store all insight content data
  main.go
  pkg/config/config.go
  pkg/processor/reportprocessor.go
  pkg/retriever/contentretriever.go
  pkg/retriever/contentretriever_test.go
  pkg/retriever/reportretriever.go
  pkg/retriever/reportretriever_test.go
Labels: approved, lgtm

#35 Add scope to PolicyReport resource
  pkg/processor/reportprocessor.go
Labels: approved, lgtm

#36 Add the -policyreport suffix to all policyreport names
  pkg/processor/reportprocessor.go
  pkg/processor/reportprocessor_test.go
Labels: approved, lgtm

#37 update content.json to remove ccx email
  test-data/content.json
Labels: approved, lgtm

#39 Add outgoing proxy for insights
  build/run-e2e-tests.sh
  pkg/retriever/contentretriever.go
  pkg/retriever/reportretriever.go
  test-data/e2e/insights-chart/templates/insights-deployment.yaml
  test-data/e2e/insights-chart/templates/insights-role.yaml
Labels: approved, lgtm

#40 include extra data for templates
  pkg/processor/reportprocessor.go
Labels: approved, lgtm

#41 remove confusing log
  pkg/processor/reportprocessor.go
  pkg/retriever/contentretriever.go
Labels: approved, lgtm

#42 Add extra logging for healthy cluster check and debugging
  pkg/processor/reportprocessor.go
  pkg/retriever/reportretriever.go
Labels: approved, lgtm
