Repository stolostron/insights-client, pull requests merged in 2022-08, with the labels that each got.

#118 do not remove local-cluster from cluster list even if it is detached
  pkg/monitor/clustermonitor.go
Labels: dco-signoff: yes, stale, no-pr-activity

#121 [2.3] Update to golang 1.18
  .travis.yml
  Dockerfile
  go.mod
Labels: lgtm, approved, dco-signoff: yes

#119 [2.5] Update to golang 1.18
  Dockerfile
  go.mod
Labels: lgtm, approved, dco-signoff: yes

#122 Updated component version to 2.7.0
  COMPONENT_VERSION
  README.md
Labels: lgtm, approved, dco-signoff: yes

#123 backport persist local cluster fix
  pkg/monitor/clustermonitor.go
Labels: dco-signoff: yes
