Repository stolostron/insights-client, pull requests merged in 2024-06, with the labels that each got.

#166 Add entitled Dockerfile for Konflux
  Dockerfile.rhtap
Labels: lgtm, approved, dco-signoff: yes

#165 Upgrade PolicyReport CRD to v1beta1
  go.mod
  go.sum
  pkg/processor/reportprocessor.go
  pkg/processor/reportprocessor_test.go
  pkg/retriever/reportretriever_test.go
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#168 [release-2.8] Update golang.org/x/net
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#171 Update golang.org/x/net
  go.mod
  go.sum
Labels: lgtm, approved
